### ISSUE TITLE
Does it working in python3？

### ISSUE THREAD

**Issue by mohhao** [zyy-cn/darknet_interface#1]
Thanks for your working , when I use python3  *.py in ubuntu, it indicates that "couldn't open file : c", but use python2 *.py it works well.

**Comment by zyy-cn** [comment]
Hi mohhao:

Thanks for your attention to my repo.Actrally I didn't test this work in python3 yet, but one of my colleague did and his test passed after fixing some bug . He told me that Python3 needs ascii to encode input parameter strings, like cfg and weights path, and I will handle this in next commit, of course you can try it yourself:) @mohhao

**Comment by zyy-cn** [comment]
@mohhao I'v already update *.py by encoding all string parameters with ascii, and I pass the test with python3 in my PC (ubuntu16.04, python3.5.5) with GPU(CUDNN). Is your problem solved?
