### ISSUE TITLE
Detection results is different from the AlexeyAB's fork.

### ISSUE THREAD

**Issue by developer0hye** [zyy-cn/darknet_interface#3]
Thank you for sharing this great source!

But I found a bug...

Detection results is different from the AlexeyAB fork.

**Comment by developer0hye** [comment]
I solved this problem.

I am going to pull requests

**Comment by zyy-cn** [comment]
Thanks for your contribution. Alexey has update his code after my forked his repo, and this is why there are difference between the two results. It's seen the time to renew this repository :)
